/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sazze.en.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RESPONSE_STATUS_CODE implements org.apache.thrift.TEnum {
  SUCCESS(200),
  INVALID(400),
  PERMISSION_DENIED(403),
  ERROR(500);

  private final int value;

  private RESPONSE_STATUS_CODE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RESPONSE_STATUS_CODE findByValue(int value) { 
    switch (value) {
      case 200:
        return SUCCESS;
      case 400:
        return INVALID;
      case 403:
        return PERMISSION_DENIED;
      case 500:
        return ERROR;
      default:
        return null;
    }
  }
}
